import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/lineup.dart';
import '../../providers/lineup_provider.dart';
import '../../../squads/models/squad.dart';

class LineupSubmissionScreen extends StatefulWidget {
  final TournamentSquad squad;
  final String matchId;

  const LineupSubmissionScreen({
    super.key,
    required this.squad,
    required this.matchId,
  });

  @override
  State<LineupSubmissionScreen> createState() => _LineupSubmissionScreenState();
}

class _LineupSubmissionScreenState extends State<LineupSubmissionScreen> {
  final Map<String, bool> _starters = {};
  final Map<String, String> _positions = {};
  final List<String> _positionOptions = ['GK', 'DF', 'MF', 'FW'];

  @override
  void initState() {
    super.initState();
    for (var id in widget.squad.playerIds) {
      _starters[id] = false;
      _positions[id] = 'MF'; // Default
    }
  }

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<LineupProvider>();

    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('SUBMIT MATCH LINEUP'),
            Text('Squad: ${widget.squad.playerIds.length} players', style: const TextStyle(fontSize: 12)),
          ],
        ),
      ),
      body: provider.isLoading 
        ? const Center(child: CircularProgressIndicator())
        : ListView.builder(
        itemCount: widget.squad.playerIds.length,
        itemBuilder: (context, index) {
          final playerId = widget.squad.playerIds[index];
          final isStarter = _starters[playerId] ?? false;

          return Card(
            margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: ListTile(
              leading: const CircleAvatar(child: Icon(Icons.person)),
              title: Text('Player $playerId'),
              subtitle: Row(
                children: [
                  const Text('Position: '),
                  DropdownButton<String>(
                    value: _positions[playerId],
                    items: _positionOptions.map((pos) => DropdownMenuItem(
                      value: pos,
                      child: Text(pos),
                    )).toList(),
                    onChanged: (val) {
                      setState(() {
                        _positions[playerId] = val!;
                      });
                    },
                  ),
                ],
              ),
              trailing: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text('Starter'),
                  Switch(
                    value: isStarter,
                    onChanged: (value) {
                      setState(() {
                        _starters[playerId] = value;
                      });
                    },
                  ),
                ],
              ),
            ),
          );
        },
      ),
      bottomNavigationBar: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ElevatedButton(
          onPressed: provider.isLoading ? null : () async {
            final players = widget.squad.playerIds.map((id) => LineupPlayer(
              playerId: id,
              isStarting: _starters[id] ?? false,
              position: _positions[id],
            )).toList();

            final lineupRequest = MatchLineup(
              id: '', // Will be generated by server
              matchId: widget.matchId,
              teamId: widget.squad.teamId,
              status: LineupStatus.SUBMITTED,
              createdAt: DateTime.now(),
              players: players,
            );

            try {
              await context.read<LineupProvider>().submitLineup(
                widget.matchId,
                lineupRequest,
              );
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Lineup submitted successfully')),
                );
                Navigator.pop(context);
              }
            } catch (e) {
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('Error: ${e.toString()}'), backgroundColor: Colors.red),
                );
              }
            }
          },
          child: provider.isLoading 
            ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
            : const Text('SUBMIT LINEUP'),
        ),
      ),
    );
  }
}
